age = input("How Old ")
height = input("How Tall? ")
weight = input("How heavy? ")
print("{}{}{}" .format("this ", "is ", "hard"))
print("So, you're {} old, {} tall and {} heavy." .format(age, height, weight))
